version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

    working_directory: ~/aws_rekognition_client

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bin/setup

      - save_cache:
          paths:
            - ./bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run tests
          command: bin/ci

      - run:
          name: run code quality checks
          command: bin/quality

      - run:
          name: send test coverage to Code Climate
          command: |
            bin/codeclimate-test-reporter '.coverage/.resultset.json'
